name: hallopak
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  chat_bubbles: ^1.4.1
  cupertino_icons: ^1.0.2
  cloud_firestore: 4.8.3
  firebase_auth: 4.7.1
  firebase_core: 2.15.0
  firebase_storage: 11.2.5
  get: 4.6.5
  get_storage: 2.1.1
  flutter:
    sdk: flutter
  image_picker: 0.8.6+4
  intl: ^0.18.1
  skeletons: ^0.0.3

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_flavorizr: 2.1.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/image/

  fonts:
    - family: BentonSans-Regular
      fonts:
        - asset: assets/fonts/BentonSans-Regular.otf
    - family: BentonSans-Book
      fonts:
        - asset: assets/fonts/BentonSans-Book.otf
    - family: BentonSans-Medium
      fonts:
        - asset: assets/fonts/BentonSans-Medium.otf
    - family: BentonSans-Bold
      fonts:
        - asset: assets/fonts/BentonSans-Bold.otf
    - family: BentonSans-Black
      fonts:
        - asset: assets/fonts/BentonSans-Black.otf

flavorizr:
  flavors:
    production:
      app:
        name: "Hallopak"
      android:
        applicationId: "com.lightsoft.hallopak"
        icon: "assets/images/logo/logo_hallopak.png"
      ios:
        bundleId: "com.lightsoft.hallopak"
        icon: "assets/images/logo/logo_hallopak.png"

    development:
      app:
        name: "[dev] Hallopak"
      android:
        applicationId: "com.lightsoft.hallopak.dev"
        icon: "assets/images/logo/logo_hallopak.png"
      ios:
        bundleId: "com.lightsoft.hallopak.dev"
        icon: "assets/images/logo/logo_hallopak.png"
