name: hallopak
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: 2.15.0
  get: 4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_flavorizr: 2.1.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/

flavorizr:
  flavors:
    production:
      app:
        name: "Hallopak"
      android:
        applicationId: "com.lightsoft.hallopak"
        icon: "assets/images/logo/icon_simpel.png"
      ios:
        bundleId: "com.lightsoft.hallopak"
        icon: "assets/images/logo/icon_simpel.png"

    development:
      app:
        name: "[dev] Hallopak"
      android:
        applicationId: "com.lightsoft.hallopak.dev"
        icon: "assets/images/logo/icon_simpel_dev.png"
      ios:
        bundleId: "com.lightsoft.hallopak.dev"
        icon: "assets/images/logo/icon_simpel_dev.png"
